### ISSUE TITLE
"TypeError: forward() takes 2 positional arguments but 3 were given" when trying to run eval.py

### ISSUE THREAD

**Issue by n00mkrad** [anishmadan23/deep3d-pytorch#3]
Hello, when I try to run eval.py, I get this error:

```
cuda
1
Traceback (most recent call last):
  File "eval.py", line 55, in <module>
    output = model(left_orig,left)
  File "D:\Software\Python38\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```

Any ideas?

**Comment by Totoro-wen** [comment]
I met same problem. Have you solved it？

**Comment by zhanghongyong123456** [comment]
> I met same problem. Have you solved it？

I  met same problem，Have you solved it
